
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/vite/.local/tools/cmake-3.31.8-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 7.1.8-1-cachyos - x86_64
...
